### ISSUE TITLE
Missing folder and a file in train_KPD/src/predict folder

### ISSUE THREAD

**Issue by danieldimit** [sjtuytc/betapose#2]
https://github.com/sjtuytc/betapose/blob/3dbf66958f94cd95f649f0f238478e581fd88d71/3_6Dpose_estimator/train_KPD/src/evaluation.py#L9

Hello I am trying to train a KPD, but I get this error:

`Traceback (most recent call last):
  File "src/train.py", line 14, in <module>
    from evaluation import prediction
  File "...\betapose\3_6Dpose_estimator\train_KPD\src\evaluation.py", line 9, in <module>
    from predict.annot.coco_minival import Mscoco_minival
ModuleNotFoundError: No module named 'predict.annot'`

Could you please upload this missing file?

**Comment by danieldimit** [comment]
nvm I just noticed it is never used. I delete it
