### ISSUE TITLE
RuntimeError: Expected object of type torch.FloatTensor but found type torch.LongTensor for argument #2 'other'

### ISSUE THREAD

**Issue by jqxxhznu** [sjtuytc/betapose#6]
Thank you for your help. I have new problems again.
`Create new model
############# Starting Epoch 0 #############
  0%|                                                 | 0/17 [00:00<?, ?it/s]Traceback (most recent call last):
  File "src/train.py", line 226, in <module>
    main()
  File "src/train.py", line 171, in main
    loss, acc = train(train_loader, m, criterion, optimizer, writer)
  File "src/train.py", line 27, in train
    for i, (inps, labels, setMask, imgset) in enumerate(train_loader_desc):
  File "/home/ltr/anaconda3/envs/betapose/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1022, in __iter__
    for obj in iterable:
  File "/home/ltr/anaconda3/envs/betapose/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/home/ltr/anaconda3/envs/betapose/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/ltr/anaconda3/envs/betapose/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ltr/anaconda3/envs/betapose/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 57, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/ltr/新加卷2/betapose/3_6Dpose_estimator/train_KPD/src/utils/dataset/coco.py", line 75, in __getitem__
    'coco', sf, self, train=self.is_train)
  File "/media/ltr/新加卷2/betapose/3_6Dpose_estimator/train_KPD/src/utils/pose.py", line 142, in generateSampleBox
    inp = rotate(inp)
  File "/media/ltr/新加卷2/betapose/3_6Dpose_estimator/train_KPD/src/torchsample/torchsample/transforms/affine_transforms.py", line 322, in __call__
    center=True)
  File "/media/ltr/新加卷2/betapose/3_6Dpose_estimator/train_KPD/src/torchsample/torchsample/utils.py", line 131, in th_affine2d
    x_transformed = th_bilinear_interp2d(x.contiguous(), new_coords)
  File "/media/ltr/新加卷2/betapose/3_6Dpose_estimator/train_KPD/src/torchsample/torchsample/utils.py", line 167, in th_bilinear_interp2d
    x0_ix = x0.mul(stride[1]).long()
RuntimeError: Expected object of type torch.FloatTensor but found type torch.LongTensor for argument #2 'other'
`

**Comment by jqxxhznu** [comment]
Does anybody know why?

**Comment by sjtuytc** [comment]
sorry I cannot reproduce your error, but the cause is clear. The second parameter should be float but not long. Do you use the same version of pytorch?
